# Generated by Django 2.0.2 on 2018-06-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_handling', '0002_auto_20180628_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Employee', 'Employee'), ('Client', 'Client')], default='C', max_length=100),
        ),
    ]
