# Generated by Django 2.0.2 on 2018-06-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_handling', '0002_auto_20180607_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
