# Generated by Django 2.0.2 on 2018-06-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_handling', '0003_auto_20180628_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_apps', 'Can view apps'),)},
        ),
    ]
