# Generated by Django 2.0.2 on 2018-06-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_handling', '0004_client_agent_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
