# Generated by Django 2.0.2 on 2018-06-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180627_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='permissions',
            new_name='permission',
        ),
    ]
